### ISSUE TITLE
Criar um protótipo para o site do produto

### ISSUE THREAD

**Issue by mazzoni2005** [SDEscobedo/referencia-rapida-git#2]
# Desenvolver o protótipo de site do produto

Dentro do nosso site, teremos, em uma página localizada no header, um breve resumo sobre o nosso projeto e nossa solução. E nessa página, estaremos redirecionando, através de um link, para outro site, que irá possuir as telas do produto e toda nossa solução detalhada.

**Comment by SDEscobedo** [comment]
Ótima prática para se iniciar no uso das issues.
